apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  initContainers:
  - name: wait-for-db
    image: busybox
    command:
    - sh
    - -c
    - until nc -z database 5432; do sleep 2; done

  containers:
  - name: web
    image: nginx
